### PR TITLE
News panel

### LINKED ISSUE #97: Move news section to the side
The news section should be updateable through Jekyll posts. Also, the news section should appear on the right side.

### PR DESCRIPTION
**Pull request by emilmelnikov**
Now we have a "News" section with the news posts, and also a sidebar on the front page that shows the latest piece of news. You can add more news by creating a Markdown file `YYYY-MM-DD-YOUR-TITLE-HERE.md` in the directory `news/_posts`. The `news/_drafts` directory can be used to store unpublished content (without the `YYYY-MM-DD` part). Consult the [Jekyll documentation](https://jekyllrb.com/docs/posts/) for more details.

I have also changed some visuals in the front page (call-to-action blocks and the intro text). Please let me know if something needs to be changed and/or reverted back.

Close #97

### CODE REVIEW

**Comment by emilmelnikov** [comment]
A follow-up suggestion: we could use the remaining space on the right to embed a twitter feed for `#ilastik` hashtag or something similar.

**Comment by emilmelnikov** [comment]
> In the current state, the ilastik description is in a grey background box. I cannot say right now if it is the design change, or that all the other elements have a grey border and white background instead - maybe I just have to get used to it, but right now it looks strange. I mean I get that these sentences are pretty special, since they describe what ilastik is in the first place. I wonder what @akreshuk or the rest of the team (@Tomaz-Vieira @m-novikov) think...

This is a kind of a lead paragraph that is supposed to catch readers' attention.

**Comment by k-dominik** [comment]
> > In the current state, the ilastik description is in a grey background box. I cannot say right now if it is the design change, or that all the other elements have a grey border and white background instead - maybe I just have to get used to it, but right now it looks strange. I mean I get that these sentences are pretty special, since they describe what ilastik is in the first place. I wonder what @akreshuk or the rest of the team (@Tomaz-Vieira @m-novikov) think...
> 
> This is a kind of a lead paragraph that is supposed to catch readers' attention.

it does.

Maybe it's the size difference of the news panel and the lead paragraph box, that makes it look so odd?

**Comment by emilmelnikov** [comment]
Also, I feel that the description on the front page is somewhat lengthy and maybe more suitable for the "About" section.

What if we replace the lead text to something like this:

> With ilastik you can leverage machine learning algorithms to easily segment, classify, track and count your cells or other experimental data.
> Most operations are interactive, even when on large datasets, so you can receive instant feedback.
> No expertise in machine learning is needed.
> Learn more... [link to the expanded version].

We can also replace "machine learning" with "AI", but this is probably too much marketing.
On a serious note, the intention is to simplify the description as much as possible for new users, but maybe this is not necessary.

**Comment by k-dominik** [comment]
> With ilastik you can leverage machine learning algorithms to easily segment, classify, track and count your cells or other experimental data.
> Most operations are interactive, even on large datasets, so you receive immediate feedback.
> No expertise in machine learning is needed.
> Learn more... [link to the expanded version].

I really like that. No user knows what lazy means in that context anyway and phrasing it _"Most operations are interactive, even on large datasets, so you receive immediate feedback"_ describes what the users actually experience.
Personally I would not want to use the term _"AI"_ with ilastik atm.

@akreshuk what do you think?

**Comment by akreshuk** [comment]
Really like the new look and description, thanks @emilmelnikov ! No AI, keep machine learning. I think the twitter feed would be good to have on the right, below the news. I think the central position of the main text is setting it apart sufficiently and we don't need the gray background in the box, we can keep it white rectangle with a gray boundary. Or at least let's try it and see how bad that looks.

**Comment by emilmelnikov** [comment]
I've inserted the timeline for `@ilastik_team`. The main text is reverted, but I've made the font look bigger. As always, waiting for the feedback.

N.B. The suggestion to replace "machine learning" with "AI" was not a serious one :)

**Comment by k-dominik** [comment]
that looks very cool! Sorry for not getting the ai joke.

Is there a way to make the space between the left items more "floaty" such that both columns end at the same height?
floaty png

also, while we are at it, the follow us at twitter thingy can potentially go now, or could be relocated to the twitter feed?

**Comment by emilmelnikov** [comment]
> Is there a way to make the space between the left items more "floaty" such that both columns end at the same height?

It is not easily possible because these elements are located in different columns, and also the timeline is actually an iframe that gets loaded by Twitter JS. You can only specify height statically through a data attribute. Maybe this is achievable with some magic (e.g. attach an event listener and change some properties when the timeline iframe is loaded), but it seems like a bad idea.

Alternatively, we can decrease the iframe's height. This won't align the blocks, but should be better anyway.

**Comment by akreshuk** [comment]
Looking great, good to merge from my side. @k-dominik ?

**Comment by k-dominik** [comment]
> Looking great, good to merge from my side. @k-dominik ?

oh absolutely - I really like the refurbished thing, having looked at it a couple of times.
I have already written a comment along these lines but it hasn't made it here...

**Comment by emilmelnikov** [comment]
Twitter timeline height has been changed to 500, and now looks good.

image

**Pull request merged**
