### PR TITLE
Add doc search

### PR DESCRIPTION
**Pull request by emilmelnikov**
Use https://docsearch.algolia.com/ for the search service.

Closes https://github.com/ilastik/ilastik.github.io/issues/164.

### CODE REVIEW

**Comment by k-dominik** [comment]
hey this looks cool! Will we get any kind of info how many searches we get (since we _only_ have 10k per month free)? Also I couldn't find what data they will collect from our users.

**Comment by emilmelnikov** [comment]
> Will we get any kind of info how many searches we get (since we _only_ have 10k per month free)?

According to https://www.algolia.com/for-open-source/, they give you 200K search queries per month.

> Also I couldn't find what data they will collect from our users.

See https://docsearch.algolia.com/docs/faq/#what-data-are-you-collecting. 

Judging by the dashboard, they don't track by default: you need to [explicitly enable tracking](https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/click-and-conversion-analytics/).

**Comment by k-dominik** [comment]
Hey @emilmelnikov, great - thank you very much for digging up those links, and also pointing me to their OSS tier!

Do we need to make people aware that by searching, they are sending their information to a third party? Can users opt out somehow?

**Comment by emilmelnikov** [comment]
> Do we need to make people aware that by searching, they are sending their information to a third party?

When you search something, the search widget contains "Search by Algolia" logo.

> Can users opt out somehow?

I don't think it's possible without sacrificing good UX.

**Comment by k-dominik** [comment]
so far so good.



> Judging by the dashboard, they don't track by default: you need to [explicitly enable tracking](https://www.algolia.com/doc/guides/getting-insights-and-analytics/search-analytics/click-and-conversion-analytics/).

so if I read this correctly, there will not be any cookies involved if we do not switch on this tracking, so for a user currently nothing would change other than enhanced features on the website.

**Comment by emilmelnikov** [comment]
> so if I read this correctly, there will not be any cookies involved if we do not switch on this tracking, so for a user currently nothing would change other than enhanced features on the website.

Yes, I checked the cookie list, and it was empty (well, not really, but all the cookies were from the Twitter widget).

**Review by k-dominik — APPROVED** [review]
great, let's merge it now that you're back :) @emilmelnikov

**Pull request merged**
