### PR TITLE
8mins sample tune for the demo videos

### PR DESCRIPTION
**Pull request by wolny**

### CODE REVIEW

**Comment by FredHamprecht** [comment]
Sorry to say, but not my taste really. 
Are we sure that a tune makes the videos better? 
If indeed so, I'd take a much longer loop (period of a minute rather than a second). 
Unfortunately I cannot make a constructive suggestion.

**Comment by FredHamprecht** [comment]
Let me explain: 
I think crappy music makes any demo video worse. 
In turn, it is hard to do excellent music justice with a demo video.

**Comment by akreshuk** [comment]
Have you seen the carving video? I think it passes well and I like it better than silence with mouse clicks.

**Comment by wolny** [comment]
I'm don't mind removing it from my video as I said in the channel already. I took me 20mins to create it on my controller (+8min to record it) so I'm not attached to it :) I've added the music just because silent 4min demo video is quite boring to watch. 

Please let me know what's the final decision on this one.

**Pull request merged**
