### PR TITLE
Polish counting

### PR DESCRIPTION
**Pull request by FynnBe**
bold, untested pull-request. before merging the "The Algorithms" section should be revised as well...

### CODE REVIEW

**Comment by k-dominik** [comment]
okay, i have just notice that I get:

```
ERROR `/documentation/counting/fig/blue_tutorial3-red.jpg' not found
```

**Comment by FynnBe** [comment]
No idea how the big caps came in there and it wasn't even trivial to rename it (needed 2 commits...?!)

**Comment by k-dominik** [comment]
haven't used it recently, but there is a `git mv <source> <destination>`

**Comment by k-dominik** [comment]
This should be fine to merge, right?

**Comment by FynnBe** [comment]
Updating the demo tutorial link still remains. I opened an issue for that: https://github.com/ilastik/ilastik.github.io/issues/52

**Pull request merged**
